### ISSUE TITLE
Onset and cessation dates in Julian Days

### ISSUE THREAD

**Issue by ogunjosam** [adrHuerta/rainfall_onset2#1]
I will like to commend the details and robustness of the Python code.  It is quite useful for my current project.

The current implementation outputs onset and cessation dates as indexes.  Is it possible to have both onset and cessation dates as Julian days (number of days from January 1)?

**Comment by adrHuerta** [comment]
Dear @ogunjosam 

I added my response for this issue in #2
Please check it

Regards
Adrian

**Comment by ogunjosam** [comment]
Thank you so much.
